name: differential-gene-expression
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - scanpy=1.9.1
  - pandas=1.5.2
  - r-base=4.2.2
  - bioconductor-mast=1.24.0
  - bioconductor-edger=3.40.0
  - bioconductor-singlecellexperiment=1.20.0
  - r-lme4
  - notebook
  - rpy2=3.5.6
  - anndata2ri=1.1
  - pip
  - pip:
      - sc-toolbox
